require:
  - rubocop-rails

AllCops:
    Exclude:
      - 'bin/**'
      - 'db/**/*'
      - 'config/**/*'
      - 'vendor/**/*'
      - 'node_modules/**/*'
      - 'test/**/*'
      - 'public/**/*'
      - 'tmp/**/*'
      - 'log/**/*'
      - !ruby/regexp /old_and_unused\.rb$/
    Rails:
      Enabled: true

AsciiComments:
    Enabled: false

Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 40

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Rails/HasAndBelongsToMany:
  Enabled: false
