version: '3'
services:
    web:
      build: .
      command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      stdin_open: true
      tty: true
      volumes:
        - .:/myapp
      ports:
        - "3000:3000"
      depends_on:
        - db
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: password
